### PR TITLE
fix: remove always duplication title

### PR DESCRIPTION
**Pull request by alswl**
Before:

* h1 (post title)
    *  h2
    *  h2

In this case, h1 is always duplicated in the article page.

After:

*   h2
*   h2

### CODE REVIEW

**Comment by ingwinlu** [comment]
thats on purpose (allows you to use top level link to 'jump' to the start of the article.

if you don't want that why not adjust `TOC_HEADERS`?

**Comment by alswl** [comment]
@ingwinlu 
What ever you adjust `TOC_HEADERS`, the TITLE of article is always display as tree root node in the table of contents.

Take a look at Wikipedia, eg. https://en.wikipedia.org/wiki/Lynx_(constellation) ,
the tables of contents did not include the article title, it's part of the article.

**Comment by ingwinlu** [comment]
You are right about the setting. Been a long time since I touched this.

However I don't see myself completely abandoning the <h0> layer as I personally like it (again mostly for the navigation as in 'jump to the top').
Do you have any interest in making this new behaviour configurable?

**Comment by alswl** [comment]
I read your blog post( https://www.heroicdebugging.biz/2017/07/22/docker-quicktips-2/ ), and I got why you want the title of article in the tree root. The floating navigator should include the title.

Let me make this configurable.

**Comment by alswl** [comment]
done.

**Comment by ingwinlu** [comment]
tyvm i will update the whole plugin soon and include your changes. probably going todo a release afterwards as well

**Comment by ingwinlu** [comment]
included via b0b8c4f3ea937b89a407148df9ea70cba6b955c4

**Pull request closed without merging**
