### PR TITLE
Optional support for non-ascii titles and some html cleanup

### PR DESCRIPTION
**Pull request by blinkov**

### CODE REVIEW

**Comment by ingwinlu** [comment]
feedback:
- not going to simply ignore some headers
- not going for additional dependencies (pyslugify)
- not going to break setup for existing users (change the wrapping div)

additionally:
- missing update in README.md as you change what is generated

however:
- I will have a look at the encoding problem
- I am open to enable configuration of the plugin where such things might be setup

**Comment by blinkov** [comment]
python-slugify makes slugs even from crazy languages like chinese, it's kind of complicated to implement the same if it's not the main  purpose of the project. As you can see it's optional and falls back to the old implementation if it's not installed

I've almost made the version where the rest of these things are configurable, but it needs some more work on tests and readme. Will let you know here when it's ready. Hope you don't get spammed with each my commit.

**Comment by ingwinlu** [comment]
- have a look at https://github.com/ingwinlu/pelican-bootstrapify/blob/master/bootstrapify.py on how default settings should be handled
- don't work on your master branch, check out some git tutorials
- i require pr's to be more neatly then my own work because I need to be able to track why stuff was done when I did not write it, so you will need to squash your commits when done

don't worry about emails, I only get them when a new comment or pr is made, not on each commit

if you prefer a more direct contact / need more help you can join the pelican irc channel

**Comment by ingwinlu** [comment]
Dear @blinkov,

I had a look at it and implemented my solution as #3. have a look if that is ok for your ascii encoding issue. For the other topics please create seperate PR's

**Comment by blinkov** [comment]
Yep, yours looks better. I haven't bothered to figure out whether pelican has it's own `slugify` function or not.
It appears to be based on different library, but whatever, the result is more or less similar.

**Pull request closed without merging**
